P2_panda_exo_manip_data_frame

In [ ]:
# On importe les bibliothèques nécessaires
import numpy as np
import pandas as pd

In [ ]:
# On lit le fichier CSV qui est dans le même dossier que ce notebook
prets = pd.read_csv('./prets.csv')

In [ ]:
# On ajoute une colonne 'endetement' qui calcule le taux d'endettement
prets['endetement'] = (prets['remboursement']*100 / prets['revenu']).round(2)

In [ ]:
# On modifie le nom de la colonne 'taux' en 'taux_interet'
prets.rename(columns={'taux': 'taux_interet'}, inplace=True)

In [ ]:
# On ajoute la colonne 'cout_total' qui calcule le coût total du prêt
prets['cout_total'] = (prets['remboursement'] * prets['duree']).round(2)

In [ ]:
# On ajoute une colonne 'benefice' qui calcule le bénéfice net du prêt
prets['benefice'] = (((prets['cout_total'] * prets['taux_interet']/100)) / 24).round(2)

In [ ]:
# on affiche les 5 prêts les plus rentables
prets.nlargest(5, 'benefice')

In [ ]:
# On met dans une variable 'clients_risque' les clients dont le taux d'endettement est supérieur à 35%
clients_risque = prets[prets['endetement'] > 35]
clients_risque.head()  # Affiche les premières lignes du DataFrame des clients à risque

In [ ]:
# On met dans une variable 'clients_risque_paris' les clients dont le taux d'endettement est supérieur à 35% de la ville de Paris
clients_risque_paris = prets[(prets['endetement'] > 35) & (prets['ville'] == 'PARIS')]
clients_risque_paris.head()  # Affiche les premières lignes du DataFrame des clients

In [ ]:
# On ajoute une colonne 'risque' qui indique si le client est à risque ou non
prets['risque'] = np.where(prets['endetement'] > 35, 'Oui', 'Non')
prets.head(20)

In [ ]:
# On affiche combien de automobiles sont financées par des prêts
nombre_automobiles_financees = prets[prets['type'] == 'automobile'].shape[0]
print(f"Nombre d'automobiles financées par des prêts : {nombre_automobiles_financees}")

# On affiche le coupt moyen total des prêts pour les préts de type 'Automobile'
cout_moyen_automobile = prets[prets['type'] == 'automobile']['cout_total'].mean().round(2)
print(f"Coût moyen total des prêts pour les prêts de type 'automobile' :{cout_moyen_automobile} €")

In [ ]:
# On affiche le bénéfice mensuel total pour l'agence de Toulouse
benefice_mensuel_toulouse = prets[prets['ville'] == 'TOULOUSE']['benefice'].sum().round(2)
print(f"Bénéfice mensuel total pour l'agence de Toulouse : {benefice_mensuel_toulouse} €")

In [ ]:
user_data = prets.groupby('identifiant').agg({
    'remboursement': 'sum',
    'endetement': 'mean',
    'cout_total': 'mean',
    'benefice': 'sum'})
user_data

In [ ]:
user_data.loc[user_data['endetement'] > 35,:]

In [ ]:
user_data_ville = prets.groupby(['ville', 'type'])['benefice'].sum()
user_data_ville

In [ ]:
prets.pivot_table(index='ville', columns='type', values='benefice', aggfunc=np.mean)

In [ ]:
clients = pd.read_csv('./clients.csv')
data = pd.merge(clients, prets, on='identifiant', how='outer')
display(data)

In [ ]:
notes = pd.read_csv('./notes.csv')
notes.head()  # Affiche les premières lignes du DataFrame ecole

In [ ]:
notes.groupby('matiere').agg({'note': ['sum', 'mean']})

In [ ]:


moy_per_stud = notes.pivot_table(index='nom', columns='matiere', values='note', aggfunc=np.mean)
moy_per_stud['moyenne'] = moy_per_stud.mean(axis=1)
moy_per_stud.loc[moy_per_stud['moyenne'] < 10, 'moyenne']

In [ ]:
notes.loc[((notes['matiere'] == 'Mathématiques') | (notes['matiere'] == 'Physique/Chimie')) & (notes['note'] >= 15), 'nom']

In [158]:
commande = pd.read_csv('./commande.csv')
commande.head()  # Affiche les premières lignes du DataFrame commande

   id  nombre
0  70       2
1  41       4
2  72       2
3  92       8
4  73       1

In [160]:
produits = pd.read_csv('./produits.csv')
produits.head()  # Affiche les premières lignes du DataFrame produits

   id  prix
0   0  24.8
1   1  13.1
2   2  23.7
3   3  16.0
4   4  19.0

In [162]:
data = pd.merge(commande, produits, on='id', how='outer')
display(data)

     id  nombre  prix
0     0       8  24.8
1     0      10  24.8
2     0       4  24.8
3     0       4  24.8
4     0       1  24.8
..   ..     ...   ...
995  99       8  11.8
996  99       1  11.8
997  99       9  11.8
998  99       9  11.8
999  99       3  11.8

[1000 rows x 3 columns]

In [172]:
data['prix_total'] = data['nombre'] * data['prix']
data['prix_total'] = data['prix_total'].round(2)
data.sort_values(by='nombre', ascending=False, inplace=True)
data.head()  # Affiche les premières lignes du DataFrame avec le prix total

     id  nombre  prix  prix_total
41    5      10  27.6       276.0
40    5      10  27.6       276.0
400  37      10  27.7       277.0
284  25      10  22.2       222.0
775  77      10  28.0       280.0